services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: konsulta-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-pension_root_2024}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-plantillas_db}
      - MYSQL_USER=${MYSQL_USER:-pension_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-pension_pass_2024}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - konsulta-network
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: konsulta-backend
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${MYSQL_USER:-pension_user}
      - DB_PASSWORD=${MYSQL_PASSWORD:-pension_pass_2024}
      - DB_NAME=${MYSQL_DATABASE:-plantillas_db}
      - CORS_ORIGINS=http://31.220.98.150:81,http://31.220.98.150,http://localhost:5173,http://127.0.0.1:5173
    volumes:
      - backend_data:/app/processed_files
    networks:
      - konsulta-network
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

  # Frontend React + Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://31.220.98.150:81/api
    container_name: konsulta-frontend
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=http://31.220.98.150:81/api
    ports:
      - "81:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - konsulta-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/cache/nginx:noexec,nosuid,size=50m
      - /var/run:noexec,nosuid,size=10m
      - /var/log/nginx:noexec,nosuid,size=50m

volumes:
  backend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/processed_files
  mysql_data:
    driver: local

networks:
  konsulta-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
    driver_opts:
      com.docker.network.bridge.name: konsulta-br0
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1500"